# Generated by Django 2.1.5 on 2019-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_holiday', models.DateField(verbose_name='First Holiday')),
                ('last_holiday', models.DateField(verbose_name='Last Holiday')),
                ('country', models.CharField(choices=[('Germany', (('DE-BW', 'Baden-Württemberg'), ('DE-BY', 'Bayern'), ('DE-BE', 'Berlin'), ('DE-BB', 'Brandenburg'), ('DE-HB', 'Bremen'), ('DE-HH', 'Hamburg'), ('DE-HE', 'Hessen'), ('DE-MV', 'Mecklenburg-Vorpommern'), ('DE-NW', 'Niedersachsen'), ('DE-NI', 'Nordrhein-Westfalen'), ('DE-RP', 'Rheinland-Pfalz'), ('DE-SL', 'Saarland'), ('DE-SN', 'Sachsen'), ('DE-ST', 'Sachsen-Anhalt'), ('DE-SH', 'Schleswig-Holstein'), ('DE-TH', 'Thüringen')))], default='DE-NW', max_length=5, verbose_name='Country')),
                ('name', models.CharField(choices=[('Germany', (('OF', 'Osterferien'), ('PF', 'Pfingstferien'), ('SF', 'Sommerferien'), ('HF', 'Herbstferien'), ('WF', 'Weihnachtsferien')))], default='SF', max_length=100, verbose_name='Holidays')),
            ],
            options={
                'verbose_name': 'School Holidays',
                'verbose_name_plural': 'School Holidays',
                'ordering': ['first_holiday'],
            },
        ),
    ]
