# Generated by Django 2.1.5 on 2019-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolholidays',
            name='country',
            field=models.CharField(choices=[('Germany', (('DE-BW', 'Baden-Württemberg'), ('DE-BY', 'Bayern'), ('DE-BE', 'Berlin'), ('DE-BB', 'Brandenburg'), ('DE-HB', 'Bremen'), ('DE-HH', 'Hamburg'), ('DE-HE', 'Hessen'), ('DE-MV', 'Mecklenburg-Vorpommern'), ('DE-NI', 'Niedersachsen'), ('DE-NW', 'Nordrhein-Westfalen'), ('DE-RP', 'Rheinland-Pfalz'), ('DE-SL', 'Saarland'), ('DE-SN', 'Sachsen'), ('DE-ST', 'Sachsen-Anhalt'), ('DE-SH', 'Schleswig-Holstein'), ('DE-TH', 'Thüringen')))], default='DE-NW', max_length=5, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='schoolholidays',
            name='last_holiday',
            field=models.DateField(blank=True, null=True, verbose_name='Last Holiday'),
        ),
    ]
